### ISSUE TITLE
ReferenceError: Invalid left-hand side in assignment

### ISSUE THREAD

**Issue by naknode** [territory-webguerillas/node-tsheetsapi#1]
First of all,

Above every library I have encountered in the Node realm, this is by far one of my favorites. async/await, pagination, promises. This is a really helpful library. Thank you.

Maybe I'm doing it wrong but I am getting `ReferenceError: Invalid left-hand side in assignment` trying to get all users.

```
      await res = res.next;
      ^^^^^^^^^
```

`index.js`:
```javascript
const {users} = require('./lib');

console.log(users());
```

and `lib.js`
```javascript
const TSheetsApi = require('tsheetsapi');

const tapi = new TSheetsApi({
    bearerToken : 'XXXX'
});

async function users() {

    let res = await tapi.users().list();

    while(res.next){
      console.log(res.data)
      await res = res.next;
    }
}

module.exports.users = users;
```

I believe I have the `async` keyword in the wrong place but I cannot for the life of me find the proper documentation on `while` loops for this kind of code execution.

Thank you for very much. Your hard work does not go unnoticed.

**Node version**: 8.7.0
**NPM version**:  5.4.2

**Comment by comppaz** [comment]
Hi @naknode,

thank you for your support.
A small test hints to a small syntax error in the await expression in your loop:

```js
res = await res.next
```

instead of:

```js
await res = res.next
```

I hope this fixes your issue!

**Comment by naknode** [comment]
Hey @comppaz , that's interesting. Never saw it like that.

My `res` query returned `null` for `res.next` so the `while` never looped. Maybe it's because it only returns if next has more listings to return? I had 25.

Anyway, my new `index.js` is:

```javascript
const { users } = require('./lib');

async function init() {
    const getUsers = await users();
    console.log(getUsers);
}

init();
```

and my new `lib.js` is:

```javascript
const TSheetsApi = require('tsheetsapi');

const tapi = new TSheetsApi({
    bearerToken : 'XXXXXXXXXXXXXXX'
});

function users() {
    return new Promise( async (resolve, reject) => {
        let res = await tapi.users().list();

        if (res.data) {
            resolve(res.data);
        } else {
            reject(`No results.`);
        }
    });
}

module.exports.users = users;
```

which seems to work fine and return all datasets. Anyway, thank you! I had forgotten `res.next` was a method I could attach `await` next too. It  all makes sense now regardless.

**Comment by comppaz** [comment]
I see your problem, unfortunately there is an error in our README.
If you call: 

```js
let res = await tapi.users().list();
```
then `res.data` will already contain the first page of results. 
Thus, this adapted version should work (untested - that's how we use this library in production):

```js
const TSheetsApi = require('tsheetsapi');

const tapi = new TSheetsApi({
    bearerToken : 'XXXX'
});

async function users() {

    let res = await tapi.users().list();

    while(res && res.data.length >0){
      console.log(res.data)
      res = await res.next;
    }
}

module.exports.users = users;
```
I'll adapt the README accordingly!

**Comment by naknode** [comment]
Awesome. Thanks @comppaz 

I see you're also _just_ providing the `body` in `doRequest()`:

```javascript
          const entries = body['results'][endpoint];

          let result = [];

          for(let key in entries){

            if(!entries.hasOwnProperty(key)) continue;

            result.push(entries[key]);

          }

          resolve([result, body["more"]]);
```

I have a use-case that makes me need `body['supplemental_data']`. Would you like me to submit a PR to make this more extensible? This PR would come with README changes as well.

**Comment by comppaz** [comment]
You're right, supplemental data wasn't included into the response. 
I just pushed a new commit (and version) that includes the supplemental data - version 2.0.7 should be available through NPM soon :-)

**Comment by naknode** [comment]
Good deal, thanks for all of your hard work!

**Comment by comppaz** [comment]
Thanks for your support! If you find any further issues, let me know.
