### ISSUE TITLE
Add an Example of Params in list in the Docs

### ISSUE THREAD

**Issue by frastlin** [territory-webguerillas/node-tsheetsapi#2]
Hello,
I am trying to use this library, but I can't figure out how the query should look. I'm doing:

    let res = await tapi.timesheets().list({
    	start_date: '2019-08-10',
    	end_date: '2019-08-10',
    })

If there was an example in the readme, it would really help.

**Comment by comppaz** [comment]
Hi @frastlin,

I just reviewed the README and added an example. 

But does your request work? It actually is the right approach - just tested the same request on our account and it did work!

**Comment by frastlin** [comment]
Yes, I got it to work. The problem was my token was expired, but I was not getting an error thrown telling me that the token was expired.
I find that many of the TSheets errors are not printed to the console, so I just get an uncaught promise exception or undefined undefined.
I can open an issue with these problems and maybe do a PR.

**Comment by comppaz** [comment]
Sorry, I was on a vacation the past weeks :)

In fact, you're absolutely right: The module could be more verbose.
So, if you want, go for it 👍
